var poiPosDoctors = {
    "type": "FeatureCollection",
    "name": "poiDoctors",
    "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
    "features": [
        { "type": "Feature", "properties": { "osm_id": "340190871", "name": "Kinderarzt Dr. Weiner", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Konstanz\",\"addr:country\"=>\"DE\",\"addr:housenumber\"=>\"149\",\"addr:postcode\"=>\"78464\",\"addr:street\"=>\"MainaustraÃŸe\",\"addr:suburb\"=>\"Allmannsdorf\",\"amenity\"=>\"doctors\",\"contact:email\"=>\"Weiner-KN@t-online.de\",\"contact:fax\"=>\"+49 7531 33091\",\"contact:phone\"=>\"+49 7531 33077\",\"contact:website\"=>\"http://www.kinderaerzteimnetz.de/aerzte/arzt_1489.html\",\"healthcare\"=>\"doctor\",\"healthcare:speciality\"=>\"paediatrics\",\"wheelchair\"=>\"no\"" }, "geometry": { "type": "Point", "coordinates": [ 9.20204, 47.68218 ] } },
        { "type": "Feature", "properties": { "osm_id": "909513967", "name": "Tierarztpraxis D. Bicking", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Konstanz\",\"addr:country\"=>\"DE\",\"addr:housenumber\"=>\"55\",\"addr:postcode\"=>\"78462\",\"addr:street\"=>\"SchottenstraÃŸe\",\"amenity\"=>\"veterinary\",\"opening_hours\"=>\"Mo-Fr 10:00-12:00, Mo,We-Fr 17:00-19:00\",\"phone\"=>\"+49753122066\",\"website\"=>\"http://www.tierarztpraxis-bicking.de\",\"wheelchair\"=>\"yes\"" }, "geometry": { "type": "Point", "coordinates": [ 9.17218, 47.66513 ] } },
        { "type": "Feature", "properties": { "osm_id": "1053895530", "name": "Dr. med. Anette Pohlmeier: Arzt fÃ¼r Allgemeinmedizin", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"doctors\",\"healthcare\"=>\"doctor\",\"healthcare:speciality\"=>\"general\"" }, "geometry": { "type": "Point", "coordinates": [ 9.00395, 47.74229 ] } },
        { "type": "Feature", "properties": { "osm_id": "1124744503", "name": "Allgemein, Zahnarzt, Physiotherapie", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"doctors\",\"healthcare\"=>\"centre\",\"healthcare:speciality\"=>\"dentist;general;physiotherapy\"" }, "geometry": { "type": "Point", "coordinates": [ 9.11564, 47.73259 ] } },
        { "type": "Feature", "properties": { "osm_id": "1124755761", "name": "Zahn, Allgemeinarzt", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"doctors\",\"operator\"=>\"Dr. Eck, Dr. Kiesel\",\"wheelchair\"=>\"yes\"" }, "geometry": { "type": "Point", "coordinates": [ 9.11577, 47.73421 ] } },
        { "type": "Feature", "properties": { "osm_id": "1837491329", "name": "Pneumologische Gemeinschaftspraxis", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Konstanz\",\"addr:country\"=>\"DE\",\"addr:housenumber\"=>\"7g\",\"addr:postcode\"=>\"78464\",\"addr:street\"=>\"LuisenstraÃŸe\",\"amenity\"=>\"doctors\",\"healthcare\"=>\"doctor\",\"website\"=>\"https://www.lungenaerzte-im-netz.de/aerzte/arzt_217_1.html\",\"wheelchair\"=>\"yes\"" }, "geometry": { "type": "Point", "coordinates": [ 9.18749, 47.67242 ] } },
        { "type": "Feature", "properties": { "osm_id": "3183076955", "name": "Zahnarzt Dr. Ekkehard Uhl", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"dentist\",\"opening_hours\"=>\"Mo,We,Th 08:00-12:00, 14:00-19:00; Tu 8:00-12:00, 14:00-17:00\",\"phone\"=>\"+49 7732 52299\",\"website\"=>\"https://www.zahnbehandlung-radolfzell.de/\",\"wheelchair\"=>\"yes\"" }, "geometry": { "type": "Point", "coordinates": [ 8.93542, 47.75362 ] } },
        { "type": "Feature", "properties": { "osm_id": "3459096493", "name": "Zahnarztpraxis Dr. Bernhart & Dr. Brezavscek", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Radolfzell am Bodensee\",\"addr:country\"=>\"DE\",\"addr:housenumber\"=>\"84\",\"addr:postcode\"=>\"78315\",\"addr:street\"=>\"SchÃ¼tzenstraÃŸe\",\"amenity\"=>\"dentist\",\"healthcare\"=>\"dentist\",\"phone\"=>\"+49 7732 99600\",\"website\"=>\"https://zahnarzt-praxis-radolfzell.de/\",\"wheelchair\"=>\"yes\",\"wheelchair:description\"=>\"Praxis befindet sich im Millennium Tower, Aufzug vorhanden\"" }, "geometry": { "type": "Point", "coordinates": [ 8.9737, 47.74684 ] } },
        { "type": "Feature", "properties": { "osm_id": "3469070199", "name": "Hausarztpraxis am Bodanplatz", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Konstanz\",\"addr:country\"=>\"DE\",\"addr:housenumber\"=>\"4\",\"addr:postcode\"=>\"78462\",\"addr:street\"=>\"Bodanplatz\",\"amenity\"=>\"doctors\",\"healthcare\"=>\"doctor\",\"healthcare:speciality\"=>\"general\",\"opening_hours\"=>\"Mo 08:30-12:00,14:00-16:00; Tu 08:30-12:00,18:00-20:00; We 08:30-12:00; Th 08:30-12:00,18:00-20:00; Fr 08:30-12:00\",\"operator\"=>\"Dr.med. Petra Zantl\",\"owner\"=>\"Dr.med. Christiane Seifert-Ibach\",\"phone\"=>\"+49 7531 61305\",\"website\"=>\"http://www.doc-konstanz.de\"" }, "geometry": { "type": "Point", "coordinates": [ 9.17406, 47.65787 ] } },
        { "type": "Feature", "properties": { "osm_id": "3815198665", "name": "Dr. Wenzler", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"dentist\",\"fax\"=>\"+49 7531 690 507\",\"healthcare\"=>\"dentist\",\"phone\"=>\"+49 7531 61291\",\"website\"=>\"https://www.zahnarzt-drwenzler.de/\",\"wheelchair\"=>\"no\"" }, "geometry": { "type": "Point", "coordinates": [ 9.18406, 47.67305 ] } },
        { "type": "Feature", "properties": { "osm_id": "3854327519", "name": "Tierarztpraxis Mascha Beszus", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Konstanz\",\"addr:country\"=>\"DE\",\"addr:housenumber\"=>\"2\",\"addr:postcode\"=>\"78467\",\"addr:street\"=>\"StifterstraÃŸe\",\"addr:suburb\"=>\"FÃ¼rstenberg\",\"amenity\"=>\"veterinary\",\"opening_hours\"=>\"Mo-Fr 17:00-19:00\",\"phone\"=>\"+4975315848997\",\"website\"=>\"http://www.beszus.de\",\"wheelchair\"=>\"no\"" }, "geometry": { "type": "Point", "coordinates": [ 9.14859, 47.68906 ] } },
        { "type": "Feature", "properties": { "osm_id": "4488041593", "name": "Facharzt Zentrum Konstanz", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"doctors\",\"healthcare\"=>\"centre\",\"name:de\"=>\"Facharzt Zentrum Konstanz\",\"wheelchair\"=>\"yes\"" }, "geometry": { "type": "Point", "coordinates": [ 9.18729, 47.6724 ] } },
        { "type": "Feature", "properties": { "osm_id": "4791936913", "name": "Augenzentrum Eckert Augenarzt / Augenlasern Konstanz", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Konstanz\",\"addr:housenumber\"=>\"1\",\"addr:postcode\"=>\"78462\",\"addr:street\"=>\"Salmannsweilergasse\",\"amenity\"=>\"doctors\",\"description\"=>\"Augenarzt und Augenlasern Konstanz- Wir behandeln Ihr Auge als wÃ¤re es unser Eigenes!\",\"email\"=>\"refraktivsprechstunde@medizentrum-eckert.de\",\"healthcare\"=>\"doctor\",\"healthcare:speciality\"=>\"ophthalmology\",\"image\"=>\"https://ml3pshjrdjsl.i.optimole.com/ZjQ_Xws-fHpi8xrY/w:600/h:400/q:90/https://augenlaserzentrum-bodensee.de/wp-content/uploads/2021/10/eckert-logo.png\",\"opening_hours\"=>\"Mo-Fr 08:00-18:00\",\"phone\"=>\"+497531 15020\",\"website\"=>\"https://augenlaserzentrum-bodensee.de/\",\"wheelchair\"=>\"yes\"" }, "geometry": { "type": "Point", "coordinates": [ 9.17655, 47.66113 ] } },
        { "type": "Feature", "properties": { "osm_id": "5277911324", "name": "Dr. Ulrike KÃ¼mmerle", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Konstanz\",\"addr:country\"=>\"DE\",\"addr:housenumber\"=>\"18\",\"addr:postcode\"=>\"78462\",\"addr:street\"=>\"Emmishofer StraÃŸe\",\"amenity\"=>\"dentist\",\"email\"=>\"info@zahnarztpraxis-kuemmerle.de\",\"healthcare\"=>\"dentist\",\"opening_hours\"=>\"Mo-Fr 08:00-19:00\",\"phone\"=>\"+49 7531 22374\"" }, "geometry": { "type": "Point", "coordinates": [ 9.16977, 47.65665 ] } },
        { "type": "Feature", "properties": { "osm_id": "5342691831", "name": "Hausarztpraxis am Tannenhof", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Konstanz\",\"addr:country\"=>\"DE\",\"addr:housenumber\"=>\"2\",\"addr:postcode\"=>\"78464\",\"addr:street\"=>\"Am Tannenhof\",\"fax\"=>\"+49 7531 958813\",\"healthcare\"=>\"doctor\",\"healthcare:speciality\"=>\"general\",\"opening_hours\"=>\"Mo-Fr 08:00-12:00; Mo-Tu 15:00-17:00; Th 13:00-15:00\",\"operator\"=>\"Nicolas Bohlender\",\"phone\"=>\"+49 7531 56789\",\"website\"=>\"https://www.praxis-am-tannenhof.de/\",\"wheelchair\"=>\"yes\"" }, "geometry": { "type": "Point", "coordinates": [ 9.19758, 47.6742 ] } },
        { "type": "Feature", "properties": { "osm_id": "5548621658", "name": "ANDREAS CHATZIIOANNIDIS", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"dentist\",\"email\"=>\"info@zahnarzt-mainaustrasse.de\",\"healthcare\"=>\"dentist\",\"website\"=>\"https://www.zahnarzt-mainaustrasse.de/\"" }, "geometry": { "type": "Point", "coordinates": [ 9.20149, 47.68059 ] } },
        { "type": "Feature", "properties": { "osm_id": "6320589590", "name": "mitsch", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Konstanz\",\"addr:country\"=>\"DE\",\"addr:housenumber\"=>\"18\",\"addr:postcode\"=>\"78462\",\"addr:street\"=>\"BrÃ¼elstraÃŸe\",\"amenity\"=>\"dentist\",\"healthcare\"=>\"dentist\",\"opening_hours\"=>\"Mo-We 8:00-12:00,14:30-18:30; Th 8:00-12:00,17:00-20:00; Fr 8:00-12:00\",\"website\"=>\"https://zahnarztpraxis-mitsch.de/\"" }, "geometry": { "type": "Point", "coordinates": [ 9.16621, 47.66396 ] } },
        { "type": "Feature", "properties": { "osm_id": "6387695052", "name": "Dr. Carola Kerner", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"amenity\"=>\"dentist\",\"contact:phone\"=>\"+49 7531 458458\",\"contact:website\"=>\"https://www.mein-zahnarzt-konstanz.de/\",\"healthcare\"=>\"dentist\",\"opening_hours\"=>\"Mo,Tu,Th 08:00-13:00,14:00-16:30; We,Fr 08:00-12:00\"" }, "geometry": { "type": "Point", "coordinates": [ 9.20222, 47.68094 ] } },
        { "type": "Feature", "properties": { "osm_id": "7008669059", "name": "Augenzentrum Eckert: Konstanz Augenarzt", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:city\"=>\"Konstanz\",\"addr:country\"=>\"DE\",\"addr:housenumber\"=>\"5\",\"addr:postcode\"=>\"78462\",\"addr:street\"=>\"MÃ¼nsterplatz\",\"amenity\"=>\"doctors\",\"email\"=>\"info@augenzentrum-eckert.de\",\"healthcare\"=>\"doctor\",\"healthcare:speciality\"=>\"ophthalmology;eye;eye_specialist_and_surgeon\",\"opening_hours\"=>\"Mo-Fr 08:00-18:00\",\"opening_hours:signed\"=>\"no\",\"opening_hours:url\"=>\"https://augenzentrum-eckert.de/standorte/konstanz-3/\",\"operator\"=>\"Augenzentrum Eckert\",\"phone\"=>\"+49 7531 15020\",\"website\"=>\"https://augenzentrum-eckert.de/standorte/konstanz-3/\"" }, "geometry": { "type": "Point", "coordinates": [ 9.17531, 47.66381 ] } },
        { "type": "Feature", "properties": { "osm_id": "9278778160", "name": "Dr. Oektem & Partner", "barrier": null, "highway": null, "ref": null, "address": null, "is_in": null, "place": null, "man_made": null, "other_tags": "\"addr:housenumber\"=>\"64\",\"addr:street\"=>\"Am Briel\",\"amenity\"=>\"dentist\",\"healthcare\"=>\"dentist\",\"opening_hours\"=>\"Mo, We 08:00-18:00; Tu, Th 08:00-19:30; Fr 08:00-14:00\",\"phone\"=>\"+491731955555\",\"website\"=>\"www.zahnarztpraxis-konstanz.de\",\"wheelchair\"=>\"yes\"" }, "geometry": { "type": "Point", "coordinates": [ 9.17402, 47.67711 ] } }

    ]
}
    